### ISSUE TITLE
Calling ActiveRecord::Base.nilify_blanks in an initializer does not seem to work

### ISSUE THREAD

**Issue by justin808** [rubiety/nilify_blanks#18]
If I create a file in config/initializers with

``` ruby
ActiveRecord::Base.nilify_blanks
```

Then no effect.

But placing this line:

``` ruby
  nilify_blanks
```

Below the declaration of my model seems to work fine. I'm using all very current gems, and the master tip of this project...

**Comment by mjy** [comment]
I seem to have the same issue.

**Comment by bartezic** [comment]
+1 - the same problem.

**Comment by bartezic** [comment]
Monkey patching working perfect:
```
class ActiveRecord::Base     
  nilify_blanks
end
```

**Comment by dgobaud** [comment]
same problem and monkey patching is not working in rails 4

**Comment by dgobaud** [comment]
only syntax is working is in every model using 

nilify_blanks :only => [:foo, :bar]

**Comment by dgobaud** [comment]
i looked at this more - problem is line 68 in https://github.com/rubiety/nilify_blanks/blob/master/lib/nilify_blanks.rb

self.nilify_blanks_columns = self.content_columns.select(&:null).select {|c| options[:types].include?(c.type) }.map(&:name).map(&:to_s)

its excluding columns that can't be null but I want it to include them and cause the error. That is one of the reasons I'm using this gem is to prevent '' from being saved - I prefer the error

**Comment by nagyt234** [comment]
Monkey patching is working in rails 4.1.9

**Comment by jibiel** [comment]
@dgobaud Better late than never — #28.

**Comment by jcavalieri** [comment]
Neither the one liner or the monkey patch seems to work for me.

Using gem 'rails', '~> 5.1', '>= 5.1.7'

**Comment by jcavalieri** [comment]
My bad, I needed to rebuild my image. Both methods i.e. the one liner and the monkey patch work.

If this isn't still an issue for others, I recommend closing this issue.

**Comment by eric-norcross** [comment]
I'm running into this issue however I can't even start the server when using the global initializer.

**Using:**
`ruby '2.6.3'`
`rails 6.0.2.2`
`puma 4.3.3`

**/initializers/nilify_blanks.rb**
`ActiveRecord::Base.nilify_blanks`

Whenever I try to start the server, I get:
`! Unable to load application: NoMethodError: undefined method 'nilify_blanks' for ActiveRecord::Base:Class
/Users/me/.rvm/gems/ruby-2.6.3@goapron/gems/activerecord-6.0.2.2/lib/active_record/dynamic_matchers.rb:22:in 'method_missing': undefined method 'nilify_blanks' for ActiveRecord::Base:Class (NoMethodError)`

I've updated bundler and tried the monkey patch but neither have worked
`
